// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mdvyidvjzluthvjtljbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1kdnlpZHZqemx1dGh2anRsamJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MDIxMDcsImV4cCI6MjA2ODE3ODEwN30.PeWNWvoZ-Q6DWGQkyZqKZg2XrbYZXXpUIWngj5pj4ao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});